### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by ekohl**
This adds basic testing for classes (uncovering a bug), a metadata file so we know we need stdlib and sets up a travis testing matrix.

### CODE REVIEW

**Comment by ekohl** [comment]
It looks like that for puppet 3 support the syntax in ```yum_repo.pp``` is invalid (inline hash). Personally I don't care about puppet 3 any more, but maybe Inuits does. Do we want to maintain puppet 3 support or can I go full puppet 4?

**Comment by LadyNamedLaura** [comment]
@ekohl for me (and inuits) the lowest common denominator is puppet 3.8.7 with future-parser, so that's 99% puppet4. So i'd be fine with putting the line there, though not sure what the requirements are for katello/puppet-pulp.

**Comment by LadyNamedLaura** [comment]
there seems to be one more issue with the acceptance tests, I'll merge when that's fixed. (I think you need a describe or context block around the `let :install_pulp` block)

**Comment by ekohl** [comment]
> @ekohl for me (and inuits) the lowest common denominator is puppet 3.8.7 with future-parser, so that's 99% puppet4. So i'd be fine with putting the line there, though not sure what the requirements are for katello/puppet-pulp.

puppet-pulp is puppet 4 only. I'll modify it for 3.8.7 with future parser then, that should be easy enough to support.

> there seems to be one more issue with the acceptance tests, I'll merge when that's fixed. (I think you need a describe or context block around the let :install_pulp block)

I was fighting with that, but slow wifi on the train didn't help.

**Comment by ekohl** [comment]
The tests still failed, not sure why the empty repo gave a bad request response. Could it be that the name is no longer allowed?

**Comment by LadyNamedLaura** [comment]
@ekohl yeah, i merged it now so i can look at that test failure more easily, I know it's not nice to have broken tests in master, but otoh, better than no tests :-)

**Comment by LadyNamedLaura** [comment]
@ekohl though it makes me think we possibly should drop the __empty__ repo, since it's use-case (which I've now quickly documented in 2fa7f80) might be a bit too specific. (and a workaround around a lacking feature in pulp)

**Comment by ekohl** [comment]
I don't think I'll have much time to look at this till next week, but I have some work in the pipeline to use pulp-admin to do additional verification. Once that all works I can test my connection refactor for which I have a branch in my repo ready but no testing (and doesn't cleanly rebase now).

**Pull request merged**
